#!/usr/local/bin/bash
#
# Copyright (c) 2016 Joyent Inc., All rights reserved.
#

. /lib/triton/lib_triton_scripts.cfg

SCRIPT=/tmp/.operator-script
rm -f $SCRIPT
$MDATA_GET_BIN sdc:operator-script >$SCRIPT
if [[ $? -eq 0 && -f $SCRIPT ]] ; then
    chmod +x $SCRIPT
    lib_triton_info "executing sdc:operator-script"
    # TODO: is this abnormally aborting with 'set -e' active?
    $SCRIPT
    operator_script_exit=$?
    if [[ ${operator_script_exit} -gt 0 ]]; then
        lib_triton_info "WARNING: operator-script failed: exited \
          ${operator_script_exit}"
    fi
fi
