#!/usr/local/bin/bash
#
# Copyright (c) 2014 Joyent Inc., All rights reserved.
# Set the hostname of the VM if it's not already configured by the user.

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

lib_smartdc_info "Start of $(basename $0) script"

grep hostname= /etc/rc.conf &>/dev/null
if [[ $? -ne 0 ]]; then
  lib_smartdc_info "No hostname set in /etc/rc.conf."
  hostname=$($MDATA_GET_BIN sdc:hostname) && \
    lib_smartdc_info "Setting hostname to sdc:hostname: $hostname."
  
  if [[ $? -ne 0 ]]; then
    lib_smartdc_info "No value set for sdc:hostname."
    hostname=$($MDATA_GET_BIN sdc:uuid) && \
      lib_smartdc_info "Setting hostname to sdc:uuid: $hostname"
    
    if [[ $? -ne 0 ]]; then
      lib_smartdc_info "No value set for sdc:uuid. Setting empty hostname."
      hostname=""
      
    fi
  fi

  if [[ ! -z "$hostname" ]]; then
    lib_smartdc_info "Restarting /etc/rc.d/hostname"
    echo hostname="\"$hostname\" # Added by smartdc. This can be modified." >> /etc/rc.conf
    /etc/rc.d/hostname restart
  fi
fi

lib_smartdc_info "End of $(basename $0) script"

exit 0
