#!/bin/sh

# PROVIDE: triton

# Adds support for Triton (and SmartOS)

. /etc/rc.subr

name="triton"
stop_cmd=":"

(/lib/smartdc/add-network-interface)
(/lib/smartdc/set-hostname)
(/lib/smartdc/set-root-authorized-keys)
if [ ! -f /lib/smartdc/.firstboot-complete-do-not-delete ] ; then
  (/lib/smartdc/firstboot)
fi
(/lib/smartdc/run-operator-script)
(/lib/smartdc/get-user-data)
(/lib/smartdc/run-user-script)
