#!/bin/sh

# PROVIDE: triton
# BEFORE: LOGIN

. /etc/rc.subr

name="triton"


start_cmd="${name}_start"
stop_cmd=":"

load_rc_config $name

triton_start()
{
  /lib/smartdc/triton
}

run_rc_command "$1"
