#!/usr/local/bin/bash

# Copyright (c) 2016 Joyent Inc., All rights reserved.
# For scripts that should be run on first boot only

# load common functions and vars
. /lib/triton/lib_triton_scripts.cfg

# Set root password if root_pw is set in the image manifest
(/lib/triton/set-rootpassword)

# Format disk
(/lib/triton/format-secondary-disk)

# Disable firstboot once all scripts are run
lib_triton_info "Disabling firstboot"
touch /lib/triton/.firstboot-complete-do-not-delete

exit 0
