#!/usr/local/bin/bash
#
# Copyright (c) 2016 Joyent Inc., All rights reserved.
#
# Get metadata user-data (via mdata-get)
# This script is executed every boot and must be executed
# before script "run-user-script"

# load common functions and vars
. /lib/triton/lib_triton_scripts.cfg

lib_triton_info "Retrieving metadata user-data"
$MDATA_GET_BIN user-data >/var/db/mdata-user-data.new
case $? in
  0)
    lib_triton_info "Metadata user-data successfuly retrieved."
    mv /var/db/mdata-user-data{.new,}
    lib_triton_info "User-data saved to /var/db/mdata-user-data."
    ;;
  1)
    lib_triton_info "Metadata user-data not defined."
    rm -f /var/db/mdata-user-data{,.new}
    ;;
  *)
    lib_triton_info "Metadata couldn't be retrieved."
    exit 1
    ;;
esac

exit 0
